[project]
name = 'ImpactChain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dac]
path = 'contracts/dac.clar'
clarity_version = 2
epoch = 2.5

[contracts.donation]
path = 'contracts/donation.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund-distribution]
path = 'contracts/fund-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
